-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "name" TEXT,
    "email" TEXT,
    "emailVerified" TIMESTAMP(3),
    "password" TEXT,
    "image" TEXT,
    "role" TEXT NOT NULL DEFAULT 'USER',

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Account" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "providerAccountId" TEXT NOT NULL,
    "refresh_token" TEXT,
    "access_token" TEXT,
    "expires_at" INTEGER,
    "token_type" TEXT,
    "scope" TEXT,
    "id_token" TEXT,
    "session_state" TEXT,

    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Session" (
    "id" TEXT NOT NULL,
    "sessionToken" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "VerificationToken" (
    "identifier" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL
);

-- CreateTable
CREATE TABLE "SiteSettings" (
    "id" TEXT NOT NULL DEFAULT 'global',
    "siteName" TEXT NOT NULL DEFAULT 'SPORTSURF',
    "logoUrl" TEXT,
    "primaryColor" TEXT NOT NULL DEFAULT '#6366f1',
    "secondaryColor" TEXT NOT NULL DEFAULT '#f59e0b',
    "fontHeading" TEXT NOT NULL DEFAULT 'Inter',
    "fontBody" TEXT NOT NULL DEFAULT 'Inter',
    "contactEmail" TEXT,
    "contactPhone" TEXT,
    "address" TEXT,
    "showCategoryBar" BOOLEAN NOT NULL DEFAULT true,
    "showTicker" BOOLEAN NOT NULL DEFAULT true,
    "statsJson" TEXT DEFAULT '[]',
    "certsJson" TEXT DEFAULT '[]',
    "ctaTitle" TEXT DEFAULT 'Ready to build your dream stadium?',
    "ctaSubtitle" TEXT DEFAULT 'Contact us to get a complete guide & quote.',
    "ctaButton" TEXT DEFAULT 'GET A QUOTE',
    "ctaLink" TEXT DEFAULT '/contact',
    "aboutText" TEXT DEFAULT 'Founded in 2013, SportSurf was born from a singular vision: to bring world-class athletic infrastructure to India.',
    "aboutOriginTitle" TEXT DEFAULT 'THE ORIGIN',
    "aboutOriginText" TEXT DEFAULT 'Today, "Antigravity" represents our next evolution ΓÇö a commitment to physics-driven design that minimizes injury risk and maximizes performance potential.',
    "valuesJson" TEXT DEFAULT '[]',
    "timelineJson" TEXT DEFAULT '[]',
    "officeHours" TEXT DEFAULT 'Mon - Sat: 9:00 AM - 7:00 PM',
    "whatsappNumber" TEXT DEFAULT '+91800SPORTSURF',
    "serviceArea" TEXT DEFAULT 'Pan India Service Availability',

    CONSTRAINT "SiteSettings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TickerUpdate" (
    "id" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "TickerUpdate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Category" (
    "id" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "description" TEXT,
    "icon" TEXT DEFAULT 'default',
    "iconSvg" TEXT,
    "navbarIconUrl" TEXT,
    "href" TEXT,
    "order" INTEGER NOT NULL DEFAULT 0,
    "imageUrl" TEXT,

    CONSTRAINT "Category_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SubCategory" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "categoryId" TEXT NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "SubCategory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "HomepageGridItem" (
    "id" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "description" TEXT,
    "imageUrl" TEXT,
    "href" TEXT,
    "order" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "HomepageGridItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "NavigationItem" (
    "id" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "href" TEXT NOT NULL,
    "order" INTEGER NOT NULL DEFAULT 0,
    "parentId" TEXT,

    CONSTRAINT "NavigationItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "HeroSection" (
    "id" TEXT NOT NULL,
    "page" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "subtitle" TEXT,
    "imageUrl" TEXT,
    "ctaText" TEXT,
    "ctaLink" TEXT,
    "textColor" TEXT NOT NULL DEFAULT '#ffffff',
    "overlayOpacity" DOUBLE PRECISION NOT NULL DEFAULT 0.4,

    CONSTRAINT "HeroSection_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Product" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "shortSpec" TEXT,
    "description" TEXT NOT NULL,
    "isNew" BOOLEAN NOT NULL DEFAULT false,
    "isFeatured" BOOLEAN NOT NULL DEFAULT false,
    "heightClass" TEXT NOT NULL DEFAULT 'h-[400px]',
    "imageUrl" TEXT,
    "imagesJson" TEXT,
    "specs" TEXT,
    "whyInvestJson" TEXT,
    "premiumBenefitsJson" TEXT,
    "servicesTitle" TEXT DEFAULT 'Premium Services',
    "servicesSubtitle" TEXT DEFAULT 'We take full ownership of your project from the ground up.',
    "servicesJson" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "subCategoryId" TEXT,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Project" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "surface" TEXT NOT NULL,
    "area" TEXT NOT NULL,
    "year" TEXT NOT NULL,
    "imageUrl" TEXT,
    "isFeatured" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Project_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Testimonial" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "institution" TEXT NOT NULL,
    "quote" TEXT NOT NULL,
    "avatar" TEXT,
    "order" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "Testimonial_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ContactRequest" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT,
    "city" TEXT,
    "surface" TEXT,
    "message" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ContactRequest_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Otp" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Otp_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId");

-- CreateIndex
CREATE UNIQUE INDEX "Session_sessionToken_key" ON "Session"("sessionToken");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_token_key" ON "VerificationToken"("token");

-- CreateIndex
CREATE UNIQUE INDEX "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier", "token");

-- CreateIndex
CREATE UNIQUE INDEX "Category_label_key" ON "Category"("label");

-- CreateIndex
CREATE UNIQUE INDEX "SubCategory_name_categoryId_key" ON "SubCategory"("name", "categoryId");

-- CreateIndex
CREATE UNIQUE INDEX "HomepageGridItem_label_key" ON "HomepageGridItem"("label");

-- CreateIndex
CREATE UNIQUE INDEX "HeroSection_page_key" ON "HeroSection"("page");

-- CreateIndex
CREATE UNIQUE INDEX "Product_slug_key" ON "Product"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "Otp_email_key" ON "Otp"("email");

-- AddForeignKey
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SubCategory" ADD CONSTRAINT "SubCategory_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "NavigationItem" ADD CONSTRAINT "NavigationItem_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "NavigationItem"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Product" ADD CONSTRAINT "Product_subCategoryId_fkey" FOREIGN KEY ("subCategoryId") REFERENCES "SubCategory"("id") ON DELETE SET NULL ON UPDATE CASCADE;



-- PostgreSQL Database Dump from database_content_dump.json

-- Data for Name: SiteSettings
INSERT INTO "SiteSettings" ("id", "siteName", "logoUrl", "primaryColor", "secondaryColor", "fontHeading", "fontBody", "contactEmail", "contactPhone", "address", "showCategoryBar", "showTicker", "statsJson", "certsJson", "ctaTitle", "ctaSubtitle", "ctaButton", "ctaLink", "aboutText", "aboutOriginTitle", "aboutOriginText", "valuesJson", "timelineJson", "officeHours", "whatsappNumber", "serviceArea") VALUES ('global', 'SPORTSURF', NULL, '#6366f1', '#f59e0b', 'Inter', 'Inter', 'info@sportsurf.in', '+91 9966109191', NULL, true, true, '[{"value":500,"suffix":"+","label":"Projects Completed"},{"value":18,"suffix":"+","label":"States Served"},{"value":200,"suffix":"+","label":"Institutional Clients"},{"value":10,"suffix":"+","label":"Years of Trust"}]', '[{"title":"ISO 9001:2015"},{"title":"FIFA Quality"},{"title":"IAAF Certified"},{"title":"BIS Approved"},{"title":"NSIC"}]', 'Ready to Build Your Dream Sports Facility?', 'Get a free consultation and site visit across India.', 'REQUEST FREE ESTIMATE', '/contact', 'Founded in 2013, SportSurf was born from a singular vision: to bring world-class athletic infrastructure to India.', 'THE ORIGIN', 'Today, "Antigravity" represents our next evolution — a commitment to physics-driven design that minimizes injury risk and maximizes performance potential.', '[]', '[]', 'Mon - Sat: 9:00 AM - 7:00 PM', '+91 9966109191', 'Pan India Service Availability');

-- Data for Name: User
INSERT INTO "User" ("id", "name", "email", "emailVerified", "password", "image", "role") VALUES ('cmmyx2ulq003fkj3tsb4lf02s', 'Admin', 'admin@sportsurf.in', NULL, '$2b$12$8V5omjca25OSJp2doWXsdejrhCCQm4muFSqe5n1CaGWn4hcIhq/Q2', NULL, 'ADMIN');
INSERT INTO "User" ("id", "name", "email", "emailVerified", "password", "image", "role") VALUES ('cmmyukyb90001tbnrqzprmygl', 's', 'b21in011@kitsw.ac.in', '2026-03-20T12:00:37.557Z', '$2b$12$8FseoJzBoUe8x49DEywe9eI4fDY0w.v8NEbdMsGHOKkGZxWgKi/gq', NULL, 'ADMIN');

-- Data for Name: Category
INSERT INTO "Category" ("id", "label", "description", "icon", "iconSvg", "navbarIconUrl", "href", "order", "imageUrl") VALUES ('cmmzs27or0009khgm2ielkk1j', 'Surface sports', NULL, 'default', NULL, NULL, NULL, 10, '/images/sports/surface_sports.png');
INSERT INTO "Category" ("id", "label", "description", "icon", "iconSvg", "navbarIconUrl", "href", "order", "imageUrl") VALUES ('cmmzs27or000akhgm430kxic9', 'Water sports', NULL, 'default', NULL, NULL, NULL, 20, '/images/sports/water_sports.png');
INSERT INTO "Category" ("id", "label", "description", "icon", "iconSvg", "navbarIconUrl", "href", "order", "imageUrl") VALUES ('cmmzs27or000bkhgmkvh210yo', 'Small sports', NULL, 'default', NULL, NULL, NULL, 30, '/images/sports/small_sports.png');
INSERT INTO "Category" ("id", "label", "description", "icon", "iconSvg", "navbarIconUrl", "href", "order", "imageUrl") VALUES ('cmmzs27or000ckhgmtoyau1lw', 'Budget sports', NULL, 'default', NULL, NULL, NULL, 40, '/images/budget_sports.png');
INSERT INTO "Category" ("id", "label", "description", "icon", "iconSvg", "navbarIconUrl", "href", "order", "imageUrl") VALUES ('cmmzs27or000dkhgm9j3dgcid', 'Sports academies', NULL, 'default', NULL, NULL, NULL, 50, '/images/sports/academic_campus.png');
INSERT INTO "Category" ("id", "label", "description", "icon", "iconSvg", "navbarIconUrl", "href", "order", "imageUrl") VALUES ('cmmzs27or000ekhgm1dtr4bx6', 'Play zones', NULL, 'default', NULL, NULL, NULL, 60, '/images/sports/play_zones.png');
INSERT INTO "Category" ("id", "label", "description", "icon", "iconSvg", "navbarIconUrl", "href", "order", "imageUrl") VALUES ('cmmzs27or000fkhgmooisx1kd', 'Adventure sports games', NULL, 'default', NULL, NULL, NULL, 70, '/images/sports/adventure_sports.png');
INSERT INTO "Category" ("id", "label", "description", "icon", "iconSvg", "navbarIconUrl", "href", "order", "imageUrl") VALUES ('cmmzs27or000gkhgm9mfp4plr', 'Challenge courses', NULL, 'default', NULL, NULL, NULL, 80, '/images/hero_sports_bg.png');
INSERT INTO "Category" ("id", "label", "description", "icon", "iconSvg", "navbarIconUrl", "href", "order", "imageUrl") VALUES ('cmmzs27or000hkhgma2q9ekgn', 'Talent scout clubs', NULL, 'default', NULL, NULL, NULL, 90, '/images/hero_indian_arena.png');

-- No data for table "SubCategory"

-- Data for Name: Product
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287o000rkhgm4bhn0zxq', 'football-turf', 'Football Turf', 'surface-sports', 'Surface sports Infrastructure', 'Complete and premium setup for Football Turf customized for maximum performance and durability.', true, true, 'h-[300px]', '/images/sports/surface_sports.png', '["/images/sports/surface_sports.png"]', '[{"label":"Category","value":"Surface sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287o000skhgmuyepxhi8', 'hockey-surface', 'Hockey Surface', 'surface-sports', 'Surface sports Infrastructure', 'Complete and premium setup for Hockey Surface customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/turf_texture.png', '["/images/turf_texture.png"]', '[{"label":"Category","value":"Surface sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287o000tkhgm5jsueo8p', 'tennis-court', 'Tennis Court', 'surface-sports', 'Surface sports Infrastructure', 'Complete and premium setup for Tennis Court customized for maximum performance and durability.', false, false, 'h-[450px]', '/images/indian_complex_detail.png', '["/images/indian_complex_detail.png"]', '[{"label":"Category","value":"Surface sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287o000ukhgm7k3ocixg', 'athletics-track', 'Athletics Track', 'surface-sports', 'Surface sports Infrastructure', 'Complete and premium setup for Athletics Track customized for maximum performance and durability.', true, false, 'h-[500px]', '/images/sports/surface_sports.png', '["/images/sports/surface_sports.png"]', '[{"label":"Category","value":"Surface sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287o000vkhgmandkp8nv', 'multi-sport-court', 'Multi-Sport Court', 'surface-sports', 'Surface sports Infrastructure', 'Complete and premium setup for Multi-Sport Court customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/turf_texture.png', '["/images/turf_texture.png"]', '[{"label":"Category","value":"Surface sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287o000wkhgm29ybwj4f', 'volleyball-court', 'Volleyball Court', 'surface-sports', 'Surface sports Infrastructure', 'Complete and premium setup for Volleyball Court customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/indian_complex_detail.png', '["/images/indian_complex_detail.png"]', '[{"label":"Category","value":"Surface sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287o000xkhgm0vzzks2j', 'netball-surface', 'Netball Surface', 'surface-sports', 'Surface sports Infrastructure', 'Complete and premium setup for Netball Surface customized for maximum performance and durability.', true, false, 'h-[450px]', '/images/sports/surface_sports.png', '["/images/sports/surface_sports.png"]', '[{"label":"Category","value":"Surface sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287o000ykhgme4lb408j', 'kabaddi-mat', 'Kabaddi Mat', 'surface-sports', 'Surface sports Infrastructure', 'Complete and premium setup for Kabaddi Mat customized for maximum performance and durability.', false, false, 'h-[500px]', '/images/turf_texture.png', '["/images/turf_texture.png"]', '[{"label":"Category","value":"Surface sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287o000zkhgmk53pjx6w', 'handball-court', 'Handball Court', 'surface-sports', 'Surface sports Infrastructure', 'Complete and premium setup for Handball Court customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/indian_complex_detail.png', '["/images/indian_complex_detail.png"]', '[{"label":"Category","value":"Surface sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287o0010khgmfzpl3ror', 'rugby-turf', 'Rugby Turf', 'surface-sports', 'Surface sports Infrastructure', 'Complete and premium setup for Rugby Turf customized for maximum performance and durability.', true, false, 'h-[400px]', '/images/sports/surface_sports.png', '["/images/sports/surface_sports.png"]', '[{"label":"Category","value":"Surface sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287o0011khgmrt9p4xon', 'swimming-pool-blocks', 'Swimming Pool Blocks', 'water-sports', 'Water sports Infrastructure', 'Complete and premium setup for Swimming Pool Blocks customized for maximum performance and durability.', true, true, 'h-[300px]', '/images/sports/water_sports.png', '["/images/sports/water_sports.png"]', '[{"label":"Category","value":"Water sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287o0012khgmbd3evsz3', 'diving-boards', 'Diving Boards', 'water-sports', 'Water sports Infrastructure', 'Complete and premium setup for Diving Boards customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/sports/water_sports.png', '["/images/sports/water_sports.png"]', '[{"label":"Category","value":"Water sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287o0013khgmvqnetivr', 'water-polo-nets', 'Water Polo Nets', 'water-sports', 'Water sports Infrastructure', 'Complete and premium setup for Water Polo Nets customized for maximum performance and durability.', false, false, 'h-[450px]', '/images/sports/water_sports.png', '["/images/sports/water_sports.png"]', '[{"label":"Category","value":"Water sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287o0014khgmtf7ahhb9', 'pool-lane-ropes', 'Pool Lane Ropes', 'water-sports', 'Water sports Infrastructure', 'Complete and premium setup for Pool Lane Ropes customized for maximum performance and durability.', true, false, 'h-[500px]', '/images/sports/water_sports.png', '["/images/sports/water_sports.png"]', '[{"label":"Category","value":"Water sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287o0015khgmcfehqa63', 'aquafitness-equipment', 'Aquafitness Equipment', 'water-sports', 'Water sports Infrastructure', 'Complete and premium setup for Aquafitness Equipment customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/sports/water_sports.png', '["/images/sports/water_sports.png"]', '[{"label":"Category","value":"Water sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287p0016khgmr2o8088t', 'starting-platforms', 'Starting Platforms', 'water-sports', 'Water sports Infrastructure', 'Complete and premium setup for Starting Platforms customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/sports/water_sports.png', '["/images/sports/water_sports.png"]', '[{"label":"Category","value":"Water sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287p0017khgm4zsem7gw', 'pool-timing-systems', 'Pool Timing Systems', 'water-sports', 'Water sports Infrastructure', 'Complete and premium setup for Pool Timing Systems customized for maximum performance and durability.', true, false, 'h-[450px]', '/images/sports/water_sports.png', '["/images/sports/water_sports.png"]', '[{"label":"Category","value":"Water sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287p0018khgm32rimrom', 'water-slide-surfaces', 'Water Slide Surfaces', 'water-sports', 'Water sports Infrastructure', 'Complete and premium setup for Water Slide Surfaces customized for maximum performance and durability.', false, false, 'h-[500px]', '/images/sports/water_sports.png', '["/images/sports/water_sports.png"]', '[{"label":"Category","value":"Water sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287p0019khgm23ay3uu5', 'surf-pool-waves', 'Surf Pool Waves', 'water-sports', 'Water sports Infrastructure', 'Complete and premium setup for Surf Pool Waves customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/sports/water_sports.png', '["/images/sports/water_sports.png"]', '[{"label":"Category","value":"Water sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287p001akhgm67d7o00s', 'kayaking-simulator', 'Kayaking Simulator', 'water-sports', 'Water sports Infrastructure', 'Complete and premium setup for Kayaking Simulator customized for maximum performance and durability.', true, false, 'h-[400px]', '/images/sports/water_sports.png', '["/images/sports/water_sports.png"]', '[{"label":"Category","value":"Water sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287p001bkhgmjc61p7by', 'table-tennis', 'Table Tennis', 'small-sports', 'Small sports Infrastructure', 'Complete and premium setup for Table Tennis customized for maximum performance and durability.', true, true, 'h-[300px]', '/images/sports/small_sports.png', '["/images/sports/small_sports.png"]', '[{"label":"Category","value":"Small sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287p001ckhgmdacsz16q', 'badminton', 'Badminton', 'small-sports', 'Small sports Infrastructure', 'Complete and premium setup for Badminton customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/sports/small_sports.png', '["/images/sports/small_sports.png"]', '[{"label":"Category","value":"Small sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287p001dkhgm5e8zogyl', 'squash', 'Squash', 'small-sports', 'Small sports Infrastructure', 'Complete and premium setup for Squash customized for maximum performance and durability.', false, false, 'h-[450px]', '/images/sports/small_sports.png', '["/images/sports/small_sports.png"]', '[{"label":"Category","value":"Small sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287p001ekhgmo02gnkqr', 'billiards', 'Billiards', 'small-sports', 'Small sports Infrastructure', 'Complete and premium setup for Billiards customized for maximum performance and durability.', true, false, 'h-[500px]', '/images/sports/small_sports.png', '["/images/sports/small_sports.png"]', '[{"label":"Category","value":"Small sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs287p001fkhgmbshr4hp0', 'foosball', 'Foosball', 'small-sports', 'Small sports Infrastructure', 'Complete and premium setup for Foosball customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/sports/small_sports.png', '["/images/sports/small_sports.png"]', '[{"label":"Category","value":"Small sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:50.868Z', '2026-03-21T03:37:50.868Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001gkhgmm40yinjy', 'pickleball', 'Pickleball', 'small-sports', 'Small sports Infrastructure', 'Complete and premium setup for Pickleball customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/sports/small_sports.png', '["/images/sports/small_sports.png"]', '[{"label":"Category","value":"Small sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001hkhgmcvaqb6ao', 'darts-board', 'Darts Board', 'small-sports', 'Small sports Infrastructure', 'Complete and premium setup for Darts Board customized for maximum performance and durability.', true, false, 'h-[450px]', '/images/sports/small_sports.png', '["/images/sports/small_sports.png"]', '[{"label":"Category","value":"Small sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001ikhgmf1jnlz7v', 'carrom', 'Carrom', 'small-sports', 'Small sports Infrastructure', 'Complete and premium setup for Carrom customized for maximum performance and durability.', false, false, 'h-[500px]', '/images/sports/small_sports.png', '["/images/sports/small_sports.png"]', '[{"label":"Category","value":"Small sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001jkhgmzz6mhwqp', 'chess-mats', 'Chess Mats', 'small-sports', 'Small sports Infrastructure', 'Complete and premium setup for Chess Mats customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/sports/small_sports.png', '["/images/sports/small_sports.png"]', '[{"label":"Category","value":"Small sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001kkhgm1zoweavi', 'arm-wrestling-table', 'Arm Wrestling Table', 'small-sports', 'Small sports Infrastructure', 'Complete and premium setup for Arm Wrestling Table customized for maximum performance and durability.', true, false, 'h-[400px]', '/images/sports/small_sports.png', '["/images/sports/small_sports.png"]', '[{"label":"Category","value":"Small sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001lkhgmaasq8gem', 'cricket-nets', 'Cricket Nets', 'budget-sports', 'Budget sports Infrastructure', 'Complete and premium setup for Cricket Nets customized for maximum performance and durability.', true, true, 'h-[300px]', '/images/basketball_court.png', '["/images/basketball_court.png"]', '[{"label":"Category","value":"Budget sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001mkhgm6e6fqrqi', 'basic-outdoor-gym', 'Basic Outdoor Gym', 'budget-sports', 'Budget sports Infrastructure', 'Complete and premium setup for Basic Outdoor Gym customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/basketball_court.png', '["/images/basketball_court.png"]', '[{"label":"Category","value":"Budget sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001nkhgm42lkwiqk', 'gully-cricket-pitch', 'Gully Cricket Pitch', 'budget-sports', 'Budget sports Infrastructure', 'Complete and premium setup for Gully Cricket Pitch customized for maximum performance and durability.', false, false, 'h-[450px]', '/images/basketball_court.png', '["/images/basketball_court.png"]', '[{"label":"Category","value":"Budget sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001okhgmovae7x98', 'basketball-hoop', 'Basketball Hoop', 'budget-sports', 'Budget sports Infrastructure', 'Complete and premium setup for Basketball Hoop customized for maximum performance and durability.', true, false, 'h-[500px]', '/images/basketball_court.png', '["/images/basketball_court.png"]', '[{"label":"Category","value":"Budget sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001pkhgmjai6j0sw', 'football-goal-post', 'Football Goal Post', 'budget-sports', 'Budget sports Infrastructure', 'Complete and premium setup for Football Goal Post customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/basketball_court.png', '["/images/basketball_court.png"]', '[{"label":"Category","value":"Budget sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001qkhgmvw9ip1i6', 'volleyball-net', 'Volleyball Net', 'budget-sports', 'Budget sports Infrastructure', 'Complete and premium setup for Volleyball Net customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/basketball_court.png', '["/images/basketball_court.png"]', '[{"label":"Category","value":"Budget sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001rkhgm3a2d9q7l', 'tug-of-war-rope', 'Tug of War Rope', 'budget-sports', 'Budget sports Infrastructure', 'Complete and premium setup for Tug of War Rope customized for maximum performance and durability.', true, false, 'h-[450px]', '/images/basketball_court.png', '["/images/basketball_court.png"]', '[{"label":"Category","value":"Budget sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001skhgmwe91nluf', 'basic-track', 'Basic Track', 'budget-sports', 'Budget sports Infrastructure', 'Complete and premium setup for Basic Track customized for maximum performance and durability.', false, false, 'h-[500px]', '/images/basketball_court.png', '["/images/basketball_court.png"]', '[{"label":"Category","value":"Budget sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001tkhgmdxfklls4', 'kho-kho-posts', 'Kho-Kho Posts', 'budget-sports', 'Budget sports Infrastructure', 'Complete and premium setup for Kho-Kho Posts customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/basketball_court.png', '["/images/basketball_court.png"]', '[{"label":"Category","value":"Budget sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001ukhgm6h64f1xq', 'jump-rope-arena', 'Jump Rope Arena', 'budget-sports', 'Budget sports Infrastructure', 'Complete and premium setup for Jump Rope Arena customized for maximum performance and durability.', true, false, 'h-[400px]', '/images/basketball_court.png', '["/images/basketball_court.png"]', '[{"label":"Category","value":"Budget sports"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001vkhgms9fyqtvo', 'cricket-academy-setup', 'Cricket Academy Setup', 'sports-academies', 'Sports academies Infrastructure', 'Complete and premium setup for Cricket Academy Setup customized for maximum performance and durability.', true, true, 'h-[300px]', '/images/sports/premium_sports_hero.png', '["/images/sports/premium_sports_hero.png"]', '[{"label":"Category","value":"Sports academies"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001wkhgmf5xvjqyi', 'football-academy-arena', 'Football Academy Arena', 'sports-academies', 'Sports academies Infrastructure', 'Complete and premium setup for Football Academy Arena customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/indian_complex_detail.png', '["/images/indian_complex_detail.png"]', '[{"label":"Category","value":"Sports academies"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001xkhgmn64fq1bt', 'tennis-academy-courts', 'Tennis Academy Courts', 'sports-academies', 'Sports academies Infrastructure', 'Complete and premium setup for Tennis Academy Courts customized for maximum performance and durability.', false, false, 'h-[450px]', '/images/sports/premium_sports_hero.png', '["/images/sports/premium_sports_hero.png"]', '[{"label":"Category","value":"Sports academies"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001ykhgm87bv3ekf', 'badminton-academy', 'Badminton Academy', 'sports-academies', 'Sports academies Infrastructure', 'Complete and premium setup for Badminton Academy customized for maximum performance and durability.', true, false, 'h-[500px]', '/images/indian_complex_detail.png', '["/images/indian_complex_detail.png"]', '[{"label":"Category","value":"Sports academies"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e3001zkhgm67j71zgi', 'swimming-academy', 'Swimming Academy', 'sports-academies', 'Sports academies Infrastructure', 'Complete and premium setup for Swimming Academy customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/sports/premium_sports_hero.png', '["/images/sports/premium_sports_hero.png"]', '[{"label":"Category","value":"Sports academies"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e30020khgmsdd9owco', 'athletics-academy-track', 'Athletics Academy Track', 'sports-academies', 'Sports academies Infrastructure', 'Complete and premium setup for Athletics Academy Track customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/indian_complex_detail.png', '["/images/indian_complex_detail.png"]', '[{"label":"Category","value":"Sports academies"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e30021khgm7zqpm6qy', 'gymnastics-hall', 'Gymnastics Hall', 'sports-academies', 'Sports academies Infrastructure', 'Complete and premium setup for Gymnastics Hall customized for maximum performance and durability.', true, false, 'h-[450px]', '/images/sports/premium_sports_hero.png', '["/images/sports/premium_sports_hero.png"]', '[{"label":"Category","value":"Sports academies"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e30022khgm4ftukrjz', 'wrestling-ring', 'Wrestling Ring', 'sports-academies', 'Sports academies Infrastructure', 'Complete and premium setup for Wrestling Ring customized for maximum performance and durability.', false, false, 'h-[500px]', '/images/indian_complex_detail.png', '["/images/indian_complex_detail.png"]', '[{"label":"Category","value":"Sports academies"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e30023khgmcpbkq6zz', 'boxing-ring', 'Boxing Ring', 'sports-academies', 'Sports academies Infrastructure', 'Complete and premium setup for Boxing Ring customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/sports/premium_sports_hero.png', '["/images/sports/premium_sports_hero.png"]', '[{"label":"Category","value":"Sports academies"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28e30024khgm6zn23ngr', 'weightlifting-area', 'Weightlifting Area', 'sports-academies', 'Sports academies Infrastructure', 'Complete and premium setup for Weightlifting Area customized for maximum performance and durability.', true, false, 'h-[400px]', '/images/indian_complex_detail.png', '["/images/indian_complex_detail.png"]', '[{"label":"Category","value":"Sports academies"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.099Z', '2026-03-21T03:37:51.099Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx0025khgmh1u5srup', 'kids-soft-play', 'Kids Soft Play', 'play-zones', 'Play zones Infrastructure', 'Complete and premium setup for Kids Soft Play customized for maximum performance and durability.', true, true, 'h-[300px]', '/images/sports/play_zones.png', '["/images/sports/play_zones.png"]', '[{"label":"Category","value":"Play zones"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx0026khgmbgifmauq', 'outdoor-playground', 'Outdoor Playground', 'play-zones', 'Play zones Infrastructure', 'Complete and premium setup for Outdoor Playground customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/sports/play_zones.png', '["/images/sports/play_zones.png"]', '[{"label":"Category","value":"Play zones"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx0027khgmy6qdbute', 'trampoline-park', 'Trampoline Park', 'play-zones', 'Play zones Infrastructure', 'Complete and premium setup for Trampoline Park customized for maximum performance and durability.', false, false, 'h-[450px]', '/images/sports/play_zones.png', '["/images/sports/play_zones.png"]', '[{"label":"Category","value":"Play zones"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx0028khgmfezaxudu', 'sandpit-area', 'Sandpit Area', 'play-zones', 'Play zones Infrastructure', 'Complete and premium setup for Sandpit Area customized for maximum performance and durability.', true, false, 'h-[500px]', '/images/sports/play_zones.png', '["/images/sports/play_zones.png"]', '[{"label":"Category","value":"Play zones"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx0029khgmuzyoj6ul', 'swing-set', 'Swing Set', 'play-zones', 'Play zones Infrastructure', 'Complete and premium setup for Swing Set customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/sports/play_zones.png', '["/images/sports/play_zones.png"]', '[{"label":"Category","value":"Play zones"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002akhgmsura8r87', 'slide-complex', 'Slide Complex', 'play-zones', 'Play zones Infrastructure', 'Complete and premium setup for Slide Complex customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/sports/play_zones.png', '["/images/sports/play_zones.png"]', '[{"label":"Category","value":"Play zones"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002bkhgm2s65chya', 'see-saw-zone', 'See-Saw Zone', 'play-zones', 'Play zones Infrastructure', 'Complete and premium setup for See-Saw Zone customized for maximum performance and durability.', true, false, 'h-[450px]', '/images/sports/play_zones.png', '["/images/sports/play_zones.png"]', '[{"label":"Category","value":"Play zones"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002ckhgmcp4da38v', 'climbing-frame', 'Climbing Frame', 'play-zones', 'Play zones Infrastructure', 'Complete and premium setup for Climbing Frame customized for maximum performance and durability.', false, false, 'h-[500px]', '/images/sports/play_zones.png', '["/images/sports/play_zones.png"]', '[{"label":"Category","value":"Play zones"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002dkhgmn1djzbt1', 'merry-go-round', 'Merry-Go-Round', 'play-zones', 'Play zones Infrastructure', 'Complete and premium setup for Merry-Go-Round customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/sports/play_zones.png', '["/images/sports/play_zones.png"]', '[{"label":"Category","value":"Play zones"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002ekhgm3o97522d', 'splash-pad', 'Splash Pad', 'play-zones', 'Play zones Infrastructure', 'Complete and premium setup for Splash Pad customized for maximum performance and durability.', true, false, 'h-[400px]', '/images/sports/play_zones.png', '["/images/sports/play_zones.png"]', '[{"label":"Category","value":"Play zones"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002fkhgmrkzbtxr8', 'rock-climbing-wall', 'Rock Climbing Wall', 'adventure-sports', 'Adventure sports games Infrastructure', 'Complete and premium setup for Rock Climbing Wall customized for maximum performance and durability.', true, true, 'h-[300px]', '/images/sports/adventure_sports.png', '["/images/sports/adventure_sports.png"]', '[{"label":"Category","value":"Adventure sports games"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002gkhgmzr4iuvi8', 'zip-line', 'Zip Line', 'adventure-sports', 'Adventure sports games Infrastructure', 'Complete and premium setup for Zip Line customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/sports/adventure_sports.png', '["/images/sports/adventure_sports.png"]', '[{"label":"Category","value":"Adventure sports games"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002hkhgmjlithz09', 'ropes-course', 'Ropes Course', 'adventure-sports', 'Adventure sports games Infrastructure', 'Complete and premium setup for Ropes Course customized for maximum performance and durability.', false, false, 'h-[450px]', '/images/sports/adventure_sports.png', '["/images/sports/adventure_sports.png"]', '[{"label":"Category","value":"Adventure sports games"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002ikhgmwxr5s5ix', 'bungee-trampoline', 'Bungee Trampoline', 'adventure-sports', 'Adventure sports games Infrastructure', 'Complete and premium setup for Bungee Trampoline customized for maximum performance and durability.', true, false, 'h-[500px]', '/images/sports/adventure_sports.png', '["/images/sports/adventure_sports.png"]', '[{"label":"Category","value":"Adventure sports games"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002jkhgmd2sj88d4', 'skate-park', 'Skate Park', 'adventure-sports', 'Adventure sports games Infrastructure', 'Complete and premium setup for Skate Park customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/sports/adventure_sports.png', '["/images/sports/adventure_sports.png"]', '[{"label":"Category","value":"Adventure sports games"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002kkhgm0vsyy8do', 'parkour-setup', 'Parkour Setup', 'adventure-sports', 'Adventure sports games Infrastructure', 'Complete and premium setup for Parkour Setup customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/sports/adventure_sports.png', '["/images/sports/adventure_sports.png"]', '[{"label":"Category","value":"Adventure sports games"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002lkhgmsrx45g79', 'archery-range', 'Archery Range', 'adventure-sports', 'Adventure sports games Infrastructure', 'Complete and premium setup for Archery Range customized for maximum performance and durability.', true, false, 'h-[450px]', '/images/sports/adventure_sports.png', '["/images/sports/adventure_sports.png"]', '[{"label":"Category","value":"Adventure sports games"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002mkhgm7cu68cpj', 'shooting-range', 'Shooting Range', 'adventure-sports', 'Adventure sports games Infrastructure', 'Complete and premium setup for Shooting Range customized for maximum performance and durability.', false, false, 'h-[500px]', '/images/sports/adventure_sports.png', '["/images/sports/adventure_sports.png"]', '[{"label":"Category","value":"Adventure sports games"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002nkhgmkn72hxmc', 'bmx-track', 'BMX Track', 'adventure-sports', 'Adventure sports games Infrastructure', 'Complete and premium setup for BMX Track customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/sports/adventure_sports.png', '["/images/sports/adventure_sports.png"]', '[{"label":"Category","value":"Adventure sports games"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002okhgmy695ncfo', 'paintball-arena', 'Paintball Arena', 'adventure-sports', 'Adventure sports games Infrastructure', 'Complete and premium setup for Paintball Arena customized for maximum performance and durability.', true, false, 'h-[400px]', '/images/sports/adventure_sports.png', '["/images/sports/adventure_sports.png"]', '[{"label":"Category","value":"Adventure sports games"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002pkhgmxnxr9pdx', 'ninja-warrior-course', 'Ninja Warrior Course', 'challenge-courses', 'Challenge courses Infrastructure', 'Complete and premium setup for Ninja Warrior Course customized for maximum performance and durability.', true, true, 'h-[300px]', '/images/turf_texture.png', '["/images/turf_texture.png"]', '[{"label":"Category","value":"Challenge courses"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002qkhgm39c8p7sv', 'military-obstacle', 'Military Obstacle', 'challenge-courses', 'Challenge courses Infrastructure', 'Complete and premium setup for Military Obstacle customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/sports/adventure_sports.png', '["/images/sports/adventure_sports.png"]', '[{"label":"Category","value":"Challenge courses"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002rkhgm74z3po9x', 'mud-run-track', 'Mud Run Track', 'challenge-courses', 'Challenge courses Infrastructure', 'Complete and premium setup for Mud Run Track customized for maximum performance and durability.', false, false, 'h-[450px]', '/images/turf_texture.png', '["/images/turf_texture.png"]', '[{"label":"Category","value":"Challenge courses"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002skhgmbdkjiwjq', 'commando-net', 'Commando Net', 'challenge-courses', 'Challenge courses Infrastructure', 'Complete and premium setup for Commando Net customized for maximum performance and durability.', true, false, 'h-[500px]', '/images/sports/adventure_sports.png', '["/images/sports/adventure_sports.png"]', '[{"label":"Category","value":"Challenge courses"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28jx002tkhgmerie64kd', 'tire-run', 'Tire Run', 'challenge-courses', 'Challenge courses Infrastructure', 'Complete and premium setup for Tire Run customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/turf_texture.png', '["/images/turf_texture.png"]', '[{"label":"Category","value":"Challenge courses"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.309Z', '2026-03-21T03:37:51.309Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28pp002ukhgmkul91pql', 'wall-climb', 'Wall Climb', 'challenge-courses', 'Challenge courses Infrastructure', 'Complete and premium setup for Wall Climb customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/sports/adventure_sports.png', '["/images/sports/adventure_sports.png"]', '[{"label":"Category","value":"Challenge courses"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.517Z', '2026-03-21T03:37:51.517Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28pp002vkhgmqfqarpm8', 'balance-beam', 'Balance Beam', 'challenge-courses', 'Challenge courses Infrastructure', 'Complete and premium setup for Balance Beam customized for maximum performance and durability.', true, false, 'h-[450px]', '/images/turf_texture.png', '["/images/turf_texture.png"]', '[{"label":"Category","value":"Challenge courses"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.517Z', '2026-03-21T03:37:51.517Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28pp002wkhgmk0frsoin', 'monkey-bars', 'Monkey Bars', 'challenge-courses', 'Challenge courses Infrastructure', 'Complete and premium setup for Monkey Bars customized for maximum performance and durability.', false, false, 'h-[500px]', '/images/sports/adventure_sports.png', '["/images/sports/adventure_sports.png"]', '[{"label":"Category","value":"Challenge courses"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.517Z', '2026-03-21T03:37:51.517Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28pp002xkhgmj4qk1p5e', 'rope-climb', 'Rope Climb', 'challenge-courses', 'Challenge courses Infrastructure', 'Complete and premium setup for Rope Climb customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/turf_texture.png', '["/images/turf_texture.png"]', '[{"label":"Category","value":"Challenge courses"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.517Z', '2026-03-21T03:37:51.517Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28pp002ykhgmq2yrnup0', 'cargo-net', 'Cargo Net', 'challenge-courses', 'Challenge courses Infrastructure', 'Complete and premium setup for Cargo Net customized for maximum performance and durability.', true, false, 'h-[400px]', '/images/sports/adventure_sports.png', '["/images/sports/adventure_sports.png"]', '[{"label":"Category","value":"Challenge courses"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.517Z', '2026-03-21T03:37:51.517Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28pq002zkhgmx8inc039', 'performance-testing-setup', 'Performance Testing Setup', 'talent-scout', 'Talent scout clubs Infrastructure', 'Complete and premium setup for Performance Testing Setup customized for maximum performance and durability.', true, true, 'h-[300px]', '/images/basketball_court.png', '["/images/basketball_court.png"]', '[{"label":"Category","value":"Talent scout clubs"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.517Z', '2026-03-21T03:37:51.517Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28pq0030khgmhl6qh222', 'video-analytics-room', 'Video Analytics Room', 'talent-scout', 'Talent scout clubs Infrastructure', 'Complete and premium setup for Video Analytics Room customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/indian_complex_detail.png', '["/images/indian_complex_detail.png"]', '[{"label":"Category","value":"Talent scout clubs"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.517Z', '2026-03-21T03:37:51.517Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28pq0031khgmlfjxbwv2', 'combine-testing-turf', 'Combine Testing Turf', 'talent-scout', 'Talent scout clubs Infrastructure', 'Complete and premium setup for Combine Testing Turf customized for maximum performance and durability.', false, false, 'h-[450px]', '/images/basketball_court.png', '["/images/basketball_court.png"]', '[{"label":"Category","value":"Talent scout clubs"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.517Z', '2026-03-21T03:37:51.517Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28pq0032khgmug2rnfwd', 'biomechanics-lab', 'Biomechanics Lab', 'talent-scout', 'Talent scout clubs Infrastructure', 'Complete and premium setup for Biomechanics Lab customized for maximum performance and durability.', true, false, 'h-[500px]', '/images/indian_complex_detail.png', '["/images/indian_complex_detail.png"]', '[{"label":"Category","value":"Talent scout clubs"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.517Z', '2026-03-21T03:37:51.517Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28pq0033khgmwa50lxeh', 'scouting-pitch', 'Scouting Pitch', 'talent-scout', 'Talent scout clubs Infrastructure', 'Complete and premium setup for Scouting Pitch customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/basketball_court.png', '["/images/basketball_court.png"]', '[{"label":"Category","value":"Talent scout clubs"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.517Z', '2026-03-21T03:37:51.517Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28pq0034khgmusg69pxw', 'speed-track', 'Speed Track', 'talent-scout', 'Talent scout clubs Infrastructure', 'Complete and premium setup for Speed Track customized for maximum performance and durability.', false, false, 'h-[400px]', '/images/indian_complex_detail.png', '["/images/indian_complex_detail.png"]', '[{"label":"Category","value":"Talent scout clubs"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.517Z', '2026-03-21T03:37:51.517Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28pq0035khgm57z7cx5w', 'agility-grid', 'Agility Grid', 'talent-scout', 'Talent scout clubs Infrastructure', 'Complete and premium setup for Agility Grid customized for maximum performance and durability.', true, false, 'h-[450px]', '/images/basketball_court.png', '["/images/basketball_court.png"]', '[{"label":"Category","value":"Talent scout clubs"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.517Z', '2026-03-21T03:37:51.517Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28pq0036khgmlb7vr2pj', 'reflex-testing', 'Reflex Testing', 'talent-scout', 'Talent scout clubs Infrastructure', 'Complete and premium setup for Reflex Testing customized for maximum performance and durability.', false, false, 'h-[500px]', '/images/indian_complex_detail.png', '["/images/indian_complex_detail.png"]', '[{"label":"Category","value":"Talent scout clubs"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.517Z', '2026-03-21T03:37:51.517Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28pq0037khgm6so26b03', 'jump-measurement', 'Jump Measurement', 'talent-scout', 'Talent scout clubs Infrastructure', 'Complete and premium setup for Jump Measurement customized for maximum performance and durability.', false, true, 'h-[300px]', '/images/basketball_court.png', '["/images/basketball_court.png"]', '[{"label":"Category","value":"Talent scout clubs"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.517Z', '2026-03-21T03:37:51.517Z', NULL);
INSERT INTO "Product" ("id", "slug", "name", "category", "shortSpec", "description", "isNew", "isFeatured", "heightClass", "imageUrl", "imagesJson", "specs", "whyInvestJson", "premiumBenefitsJson", "servicesTitle", "servicesSubtitle", "servicesJson", "createdAt", "updatedAt", "subCategoryId") VALUES ('cmmzs28pq0038khgma8x6858b', 'tactical-board-room', 'Tactical Board Room', 'talent-scout', 'Talent scout clubs Infrastructure', ' and premium setup for Tactical Board Room customized for maximum performance and durability.', true, false, 'h-[400px]', '/images/indian_complex_detail.png', '["/images/indian_complex_detail.png"]', '[{"label":"Category","value":"Talent scout clubs"},{"label":"Design","value":"Custom"}]', NULL, NULL, 'Premium Services', 'We take full ownership of your project from the ground up.', NULL, '2026-03-21T03:37:51.517Z', '2026-03-21T03:37:51.517Z', NULL);

-- Data for Name: Project
INSERT INTO "Project" ("id", "name", "city", "state", "surface", "area", "year", "imageUrl", "isFeatured", "createdAt", "updatedAt") VALUES ('cmmzs28yg0039khgmsai9n5c9', 'Delhi Public School Sports Complex', 'New Delhi', 'Delhi', 'Synthetic Turf', '8,400 sqm', '2023', '/images/project_1.png', true, '2026-03-21T03:37:51.833Z', '2026-03-21T03:37:51.833Z');
INSERT INTO "Project" ("id", "name", "city", "state", "surface", "area", "year", "imageUrl", "isFeatured", "createdAt", "updatedAt") VALUES ('cmmzs28yg003akhgmpdfjp9s0', 'St. Xavier''s International Arena', 'Mumbai', 'Maharashtra', 'Running Track', '4,200 sqm', '2022', '/images/project_2.png', true, '2026-03-21T03:37:51.833Z', '2026-03-21T03:37:51.833Z');
INSERT INTO "Project" ("id", "name", "city", "state", "surface", "area", "year", "imageUrl", "isFeatured", "createdAt", "updatedAt") VALUES ('cmmzs28yg003bkhgmt5gorhx7', 'Lalit Modi Stadium Refurbishment', 'Bangalore', 'Karnataka', 'Multi-Sport Flooring', '12,000 sqm', '2024', '/images/indian_urban_turf.png', true, '2026-03-21T03:37:51.833Z', '2026-03-21T03:37:51.833Z');

-- Data for Name: Testimonial
INSERT INTO "Testimonial" ("id", "name", "institution", "quote", "avatar", "order") VALUES ('cmmzs2981003ckhgm9rjbffso', 'Dr. Arvind Kumar', 'Director, DPS Global', 'SportSurf Antigravity transformed our campus. Their engineering precision is unlike anything we''ve seen in India.', NULL, 0);
INSERT INTO "Testimonial" ("id", "name", "institution", "quote", "avatar", "order") VALUES ('cmmzs2981003dkhgmh7wdntx5', 'Sarah Mehra', 'Sports Coordinator, Heritage School', 'The quality of the synthetic turf is world-class. Our students are performing at higher levels with less injury risk.', NULL, 10);

-- Data for Name: HeroSection
INSERT INTO "HeroSection" ("id", "page", "title", "subtitle", "imageUrl", "ctaText", "ctaLink", "textColor", "overlayOpacity") VALUES ('cmmzs29gf003ekhgm2c0q93xt', 'home', 'India''s Premiere Sports Infrastructure Powerhouse', 'ENGINEERING EXCELLENCE FOR THE NEXT GENERATION OF ATHLETES.', '/images/hero_indian_arena.png', 'Explore Solutions', '/products', '#ffffff', 0.4);

-- Data for Name: HomepageGridItem
INSERT INTO "HomepageGridItem" ("id", "label", "description", "imageUrl", "href", "order") VALUES ('cmmzs27xq000ikhgmgf6uz0vn', 'Surface sports', 'Premium Surface sports solutions customized for performance.', '/images/sports/surface_sports.png', '/products?category=surface-sports', 10);
INSERT INTO "HomepageGridItem" ("id", "label", "description", "imageUrl", "href", "order") VALUES ('cmmzs27xq000jkhgmpvznrj7p', 'Water sports', 'Premium Water sports solutions customized for performance.', '/images/sports/water_sports.png', '/products?category=water-sports', 20);
INSERT INTO "HomepageGridItem" ("id", "label", "description", "imageUrl", "href", "order") VALUES ('cmmzs27xq000kkhgm130og38t', 'Small sports', 'Premium Small sports solutions customized for performance.', '/images/sports/small_sports.png', '/products?category=small-sports', 30);
INSERT INTO "HomepageGridItem" ("id", "label", "description", "imageUrl", "href", "order") VALUES ('cmmzs27xq000lkhgmraqylios', 'Budget sports', 'Premium Budget sports solutions customized for performance.', '/images/budget_sports.png', '/products?category=budget-sports', 40);
INSERT INTO "HomepageGridItem" ("id", "label", "description", "imageUrl", "href", "order") VALUES ('cmmzs27xq000mkhgmj8q5mldd', 'Sports academies', 'Premium Sports academies solutions customized for performance.', '/images/sports/academic_campus.png', '/products?category=sports-academies', 50);
INSERT INTO "HomepageGridItem" ("id", "label", "description", "imageUrl", "href", "order") VALUES ('cmmzs27xq000nkhgmnnlm5eig', 'Play zones', 'Premium Play zones solutions customized for performance.', '/images/sports/play_zones.png', '/products?category=play-zones', 60);
INSERT INTO "HomepageGridItem" ("id", "label", "description", "imageUrl", "href", "order") VALUES ('cmmzs27xq000okhgmttc2v9jk', 'Adventure sports games', 'Premium Adventure sports games solutions customized for performance.', '/images/sports/adventure_sports.png', '/products?category=adventure-sports-games', 70);
INSERT INTO "HomepageGridItem" ("id", "label", "description", "imageUrl", "href", "order") VALUES ('cmmzs27xq000pkhgmnrcpbqce', 'Challenge courses', 'Premium Challenge courses solutions customized for performance.', '/images/hero_sports_bg.png', '/products?category=challenge-courses', 80);
INSERT INTO "HomepageGridItem" ("id", "label", "description", "imageUrl", "href", "order") VALUES ('cmmzs27xq000qkhgmv141g743', 'Talent scout clubs', 'Premium Talent scout clubs solutions customized for performance.', '/images/hero_indian_arena.png', '/products?category=talent-scout-clubs', 90);

-- Data for Name: NavigationItem
INSERT INTO "NavigationItem" ("id", "label", "href", "order", "parentId") VALUES ('cmmzs276s0000khgm3yzb6fjc', 'Home', '/', 10, NULL);
INSERT INTO "NavigationItem" ("id", "label", "href", "order", "parentId") VALUES ('cmmzs276s0001khgm89g4w18n', 'Products', '/products', 20, NULL);
INSERT INTO "NavigationItem" ("id", "label", "href", "order", "parentId") VALUES ('cmmzs276s0002khgmhc2en94c', 'Projects', '/projects', 30, NULL);
INSERT INTO "NavigationItem" ("id", "label", "href", "order", "parentId") VALUES ('cmmzs276s0003khgmzg848h36', 'About Us', '/about', 40, NULL);
INSERT INTO "NavigationItem" ("id", "label", "href", "order", "parentId") VALUES ('cmmzs276s0004khgm2pxagx7y', 'Contact', '/contact', 50, NULL);

-- Data for Name: TickerUpdate
INSERT INTO "TickerUpdate" ("id", "text", "order") VALUES ('cmmzs27fr0005khgmtgtzvy3h', 'Free site visit & consultation across India', 10);
INSERT INTO "TickerUpdate" ("id", "text", "order") VALUES ('cmmzs27fr0006khgmfpfo38a2', 'ISO 9001:2015 Certified', 20);
INSERT INTO "TickerUpdate" ("id", "text", "order") VALUES ('cmmzs27fr0007khgm05pl10bg', 'FLAT 10% OFF on first project', 30);
INSERT INTO "TickerUpdate" ("id", "text", "order") VALUES ('cmmzs27fr0008khgmb5sef2e4', 'Premium Sports Surfaces & Equipment', 40);

